name: Build
on: 
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: string
        description: "environment to run"
        default: "dev"
  push:
    branches:
      - main
    paths-ignore: 
      .github/workflows/*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: output
        run: ls -shla
      - name: "pull code"
        uses: actions/checkout@v4       
      - name: output
        run: ls -shla
      - name: build
        run: |
          dotnet build
      - name: test
        run: |
          dotnet test
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: output
        run: ls -shla
      - name: "pull code"
        uses: actions/checkout@v4
      - name: build release
        run: |
          dotnet publish -c Release
      - name: deploy
        run: |
          echo "deploying"
          sleep 20
          echo "deployed"