name: build-dev
on:
  push:
    branches:
      - main
jobs:
  pull_var:
    runs-on: ubuntu-latest
    environment: dev
    outputs:
      server_location: ${{ steps.set-server-location.outputs.server_location }}
    steps:
      - name: set server var
        id: set-server-location
        run: |
          echo "server_location=${{vars.SERVER_LOCATION}}" >> $GITHUB_OUTPUT
          echo "environment=${{vars.SERVER_LOCATION}}"
      - name: show local output
        run: |
          echo "server_location=${{steps.set-server-location.outputs.server_location}}"
  build_dev:
    needs: pull_var    
    uses: ./.github/workflows/build.yaml
    with:
      environment: ${{needs.pull_var.outputs.server_location}}
    

