name: build-dev
on:
  push:
    branches:
      - main
jobs:
  pull_var:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: set server var
        id: set-server-location
        run: echo "SERVER_LOCATION=${{vars.SERVER_LOCATION}}" >> $GITHUB_ENV
  build_dev:
    needs: pull_var    
    uses: ./.github/workflows/build.yaml
    with:
      environment: mandalorian
    

