name: Build
on: [workflow_dispatch,push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: output
        run: ls -shla
      - name: "pull code"
        uses: actions/checkout@v4       
      - name: output
        run: ls -shla
      - name: build
        run: |
          dotnet build
      - name: test
        run: |
          dotnet test
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: output
        run: ls -shla
      - name: "pull code"
        uses: actions/checkout@v4       
      - name: deploy
        run: |
          echo "deploying"
          sleep 10
          echo "deployed"