name: gh1
on: 
  workflow_dispatch:
  workflow_call:
    inputs:
      environment:
        required: false
        type: string
        description: "environment to run"
        default: "dev"
  
jobs:
  gh1:
    runs-on: ubuntu-latest
    environment: input.environment
    steps:
    - name: github output
      run: echo " ${{toJson( github)}}"
    - name: runner output
      run: echo " ${{toJson( runner)}}"
    - name: env vars output
      run: echo " ${{ toJson(vars)}}"
    - name: "conditions"
      run: echo "conditioned run"
      if: ${{vars.runner=='true'}}
            