name: gh1
on: 
  workflow_dispatch:
jobs:
  gh1:
    runs-on: ubuntu-latest
    # runs-on: ['self-hosted', 'Linux', 'X64']
    environment: dev
    steps:
    - name: github output
      run: echo " ${{toJson( github)}}"
    - name: runner output
      run: echo " ${{toJson( runner)}}"
    - name: env vars output
      run: echo " ${{ toJson(vars)}}"
    - name: "conditions"
      run: echo "conditioned run"
      if: ${{vars.runner=='true'}}
    - name: "long ops"
      run: |
        echo "run"
        sleep 30
        echo "done"
            