name: gh1
on: 
  workflow_dispatch:
jobs:
  gh1:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: github output
      run: echo " ${{toJson( github)}}"
    - name: runner output
      run: echo " ${{toJson( runner)}}"
    - name: env output
      run: echo " ${{toJson( env)}}"
            